server:
  port: 8083
spring:
  application:
    name: book-service  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhongzeyu?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: '{cipher}ce5d56378198755defd4f1ed901a63145c446605947540786a6824fbe86a3a27'
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    region: default
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: book
    prefer-ip-address: true 
