server:
  port: 8082
spring:
  application:
    name: discovery
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka/
    register-with-eureka: false
    fetch-registry: false
