server:
  port: 80
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8082/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true
    
    
spring:
  application:
    name: gateway      
zuul:
  ignored-services: "*"
  routes:
    mybook.serviceId: book-service
    mybook.path: /book/**
    sensitive-headers: Set-Cookie,Authorization 
