server:
  port: 80
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true
    
    
spring:
  application:
    name: gateway      
